name: Build And Test

on:
  push:
    branches:
      - master

env:
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  PORT: ${{ secrets.PORT }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v2

      # Install nodejs
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'

      # Install Jest
      - name: Install jest
        run: npm install -g jest

      # Install npm dependecies
      - name: Install npm dependencies
        working-directory: ./app
        run: npm install

      # Run tests
      - name: Run Tests
        working-directory: ./app
        run: npm test
        env:
          CI: true
          ISOLATE: true
